name: Mathieu Savage
favicon: null
layout_spectrum: 0.25578
typography_spectrum: 0.65774
title: Mathieu Savage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#ff0000'
    - '#ff0000'
    - '#ff0000'
    - '#ff0000'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
