name: Mathieu Savage
favicon: null
layout_spectrum: 0.4535870486870408
typography_spectrum: 0.4817527886480093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1531446515582502
  lightness: 0.41051769885234535
  saturation: 0.24080953164957464
  rhythmicContrast: 0.23367522424086928
purpose: []
